### ISSUE TITLE
Thank you so much but there is still one

### ISSUE THREAD

**Issue by allansop** [englishtea21/spammers-hunter#1]

**Comment by englishtea21** [comment]
Waiting for issue description.

**Comment by englishtea21** [comment]
Waiting for issue description.

**Comment by allansop** [comment]
![image](https://github.com/user-attachments/assets/8185a113-fb9d-4986-b526-6867177c9ce7)

Both of them
Stole my last money..... they are coward please make them pay

**Comment by allansop** [comment]
![image](https://github.com/user-attachments/assets/3dce834f-e32b-4f3c-ae34-a16c570f8c32)

![image](https://github.com/user-attachments/assets/c10e25e4-c1f7-4983-8238-c077947d4e9c)

![image](https://github.com/user-attachments/assets/506997cd-eebf-4ea5-8a91-3a6d5b619dc2)

![image](https://github.com/user-attachments/assets/c353d336-56f7-4e24-9275-1901718b0a3e)

**Comment by allansop** [comment]
They actually stole from me all the money I had left please help me make them pay. I beg you

**Comment by englishtea21** [comment]
Irrelevant issue.

**Comment by allansop** [comment]
I did this because they stall all I had…..
